import Head from "next/head";

import Navbar from "../components/navbar/Navbar";
import Banner from "../components/brand_solutions/Banner";
import Footer from "../components/footer/Footer";
import Solutions from "../components/brand_solutions/Solutions";

const brandSolutions = () => {
  return (
    <div>
      <Head>
        <title>Brand Solutions - WeedOrganics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Solutions />
      <Footer />
    </div>
  );
};

export default brandSolutions;
