import React from "react";
import Head from "next/head";

import Navbar from "../components/navbar/Navbar";
import Banner from "../components/solutions/Banner";
import Footer from "../components/footer/Footer";
import Solutions from "../components/solutions/RetailSolutions";
import Question from "../components/solutions/Question";
import image from "../public/hc.jpg";
import GeneralQuestions from "../components/help/GeneralQuestions";

const helpCenter = () => {
  return (
    <div>
      <Head>
        <title>Help Center - WeedOrganics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner src={image} title="Need Any Help?" bgType={true} />
      <GeneralQuestions />
      <Question />
      <Footer />
    </div>
  );
};

export default helpCenter;
