import Head from "next/head";

import Navbar from "../components/navbar/Navbar";
import Banner from "../components/Banner";
import Solutions from "../components/solution/Solutions";
import GrowBusiness from "../components/GrowBusiness";
import Footer from "../components/footer/Footer";

export default function Home() {
  return (
    <div className="bg-secondary">
      <Head>
        <title>WeedOrganics For Business</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Solutions />
      <GrowBusiness />
      <Footer />
    </div>
  );
}
