import Head from "next/head";

import Navbar from "../components/navbar/Navbar";
import Banner from "../components/solutions/Banner";
import Footer from "../components/footer/Footer";
import Solutions from "../components/solutions/RetailSolutions";
import Question from "../components/solutions/Question";
import image from "../public/retail_banner.png";

const retailSolutions = () => {
  return (
    <div>
      <Head>
        <title>Retail Solutions - WeedOrganics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner src={image} title="Retail Solutions" />
      <Solutions />
      <Question />
      <Footer />
    </div>
  );
};

export default retailSolutions;
